//Configuration I as in
//Daniel N. Goetzmann. Spartacus: A Tableau Prover for Hybrid Logic.
//Master's thesis, Saarland University, 2009. pp. 64-66.
//This profile mimics the behavior of Spartacus 1.0. We recommend
//using the new version: 1a.conf

--exp-ord=[@nAE<|
--dia-new
--disj-old
--blockingds=tree
--disj-ord=Np<[@EnA&
--backjumping=on
--blocking=eager
--bcp=eager
--db=on
--lazy=prop+box
--caching=off
--succ-merge
