//based on Configuration I as in
//Daniel N. Goetzmann. Spartacus: A Tableau Prover for Hybrid Logic.
//Master's thesis, Saarland University, 2009. pp. 64-66.
//This is the default configuration of version 1.1.

--exp-ord=[@nAE<|
--dia-new
--disj-old
--blockingds=tree
--disj-ord=Np<[@EnA&
--backjumping=on
--blocking=eager
--bcp=eager
--db=on
--lazy=on
--caching=off
--succ-exp
